language: php

sudo: false

php:
    - 5.6
    - 7.0

matrix:
    allow_failures:
        - php: 7.0
    fast_finish: true

before_install:
  - composer self-update

before_script:
  - phpenv config-add ./Tests/travis.php.ini
  - phpenv config-rm xdebug.ini
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit

notifications:
    email: false