version: "2"
services:
  testenv:
    image: php:7-alpine
    volumes:
      - ./:/usr/src/myapp
    command: /usr/src/myapp/vendor/bin/phpunit /usr/src/myapp/tests/ --bootstrap /usr/src/myapp/tests/bootstrap.php
